environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://mocki.io/v1/55844f7b-1882-4b38-b1ab-06a18dcd6d22'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost
