environments:
    - name:
      configs:
          endpoints:
              production:
                  url:
              sandbox:
                  url:
          security:
              enabled:
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal:
                deploymentEnvironment:
                deploymentVhost:
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:
          certs:
              - hostName:
                alias:
                path:
              - hostName:
                alias:
                path:
          mutualSslCerts:
              - tierName:
                alias:
                path:
              - tierName:
                alias:
                path:
          policies:
              - 
              -  
