environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://petstore.swagger.io/v2/swagger.json'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost
